/** User-facing strings for Swap / Pools / Buy (English). Kept in one place so i18n can be added later. */
export const S = {
  common: {
    network: (label: string) => `${label}`,
    cancel: "Cancel",
    back: "Back",
    close: "Close",
    retry: "Try again",
    loading: "Loading…",
    signedLocally: "Signed in this browser with your ML-DSA-65 key. Your key never leaves this page.",
    signedByExtension: "Your RougeChain extension will ask you to approve this transaction.",
    submittedNextBlock: "Submitted — it confirms in the next block.",
  },
  gate: {
    noneTitle: "Connect a wallet",
    noneBody: "Create, import or connect a RougeChain wallet to trade and provide liquidity.",
    openWallet: "Open wallet",
    lockedTitle: "Wallet locked",
    lockedBody: "Unlock your wallet to sign.",
    noSigner: "This wallet can't sign here. Connect the RougeChain extension or unlock a local wallet.",
  },
  swap: {
    eyebrow: "Trade / Swap",
    title: "Swap",
    heading: ["A clear path", "between assets."],
    intro: "Swap on RougeChain's native AMM. Every trade is quoted by the node, reviewed by you, and signed with post-quantum keys.",
    principles: ["Review every detail", "Understand your settings", "Clear feedback at every step"],
    ammInfo: "Constant-product AMM (x·y=k) with a 0.3% fee that goes to liquidity providers.",
    multiHop: "No direct pool? The node routes through XRGE pairs automatically (multi-hop).",
    settings: "Quote settings",
    slippage: "Slippage tolerance",
    slippageCustom: "Custom slippage (%)",
    youPay: "You pay",
    youReceive: "You receive",
    estimated: "Estimated",
    balance: (b: string) => `Balance ${b}`,
    max: "Max",
    payToken: "Pay token",
    receiveToken: "Receive token",
    reverse: "Reverse token pair",
    gettingQuote: "Getting quote…",
    noRoute: "No route found for this pair",
    quoteUnavailable: "Quote unavailable — the node didn't answer. Try again.",
    rate: "Rate",
    priceImpact: "Price impact",
    minReceived: "Minimum received",
    route: "Route",
    networkLabel: "Network",
    highImpact: (pct: string) => `High price impact: ${pct}. You may receive much less than the market price.`,
    samePair: "Choose two different tokens.",
    selectToken: "Select a token",
    button: {
      enterAmount: "Enter an amount",
      selectToken: "Select a token",
      insufficient: (s: string) => `Insufficient ${s} balance`,
      noRoute: "No route",
      quoting: "Getting quote…",
      review: "Review swap",
      sign: "Sign and swap",
      signing: "Signing…",
    },
    review: "Review swap",
    reviewNote: "Output is estimated. If the price moves more than your slippage tolerance before the block, the swap fails and nothing is spent but the network fee.",
    buyLink: "Buy XRGE with ETH or USDC on Base",
    poolsLink: "Pools and liquidity",
    usd: (v: string) => `≈ ${v}`,
  },
  picker: {
    title: "Select a token",
    search: "Search tokens",
    none: "No tokens",
    noMatch: (q: string) => `No token matches “${q}”`,
    held: (b: string) => `Balance ${b}`,
  },
  pools: {
    eyebrow: "Trade / Liquidity",
    title: "Liquidity pools",
    positionsTitle: "Your positions",
    intro: "Provide liquidity and earn 0.3% of every swap through your pool.",
    tabs: { pools: "All pools", positions: "Your positions" },
    search: "Search pools by token symbol",
    newPool: "New pool",
    swap: "Swap",
    loading: "Loading pools…",
    error: "Couldn't load pools from the node.",
    emptyTitle: "No pools yet",
    emptyBody: "Create the first pool to start trading on this network.",
    noMatch: (q: string) => `No pool matches “${q}”.`,
    noPositionsTitle: "No positions",
    noPositionsBody: "Add liquidity to a pool and your position appears here.",
    positionsNeedWallet: "Connect a wallet to see your liquidity positions.",
    showAll: (n: number) => `Show all ${n} pools`,
    fee: (pct: string) => `Fee ${pct}`,
    reserve: (s: string) => `${s} reserve`,
    lpSupply: "LP supply",
    yourLp: "Your LP",
    share: "Pool share",
    tvl: "Liquidity",
    details: "Details",
    add: "Add",
    remove: "Remove",
    uncollected: "Uncollected fees",
    calculating: "Calculating…",
    unavailable: "Unavailable for this position",
    collect: "Collect fees",
    nothingToCollect: "Nothing to collect yet",
    earnInfoTitle: "Earn from every swap",
    earnInfo:
      "Liquidity providers earn 0.3% on all trades, proportional to their share of the pool. Fees compound into the pool — use Collect fees to withdraw just your earnings and keep your deposit in place.",
  },
  liquidity: {
    addTitle: (pair: string) => `Add liquidity · ${pair}`,
    removeTitle: (pair: string) => `Remove liquidity · ${pair}`,
    collectTitle: (pair: string) => `Collect fees · ${pair}`,
    createTitle: "Create a pool",
    amount: (s: string) => `${s} amount`,
    tokenA: "Token A",
    tokenB: "Token B",
    ratioHint: "Amounts follow the pool's current ratio, so adding doesn't move the price.",
    firstLiquidity: "This pool is empty: your amounts set its starting price.",
    lpAmount: "LP tokens to remove",
    lpBalance: (b: string) => `Your balance: ${b} LP`,
    youReceive: "You receive approximately",
    youDeposit: "You deposit",
    createFee: "Pool creation fee: 10 XRGE. You receive LP tokens for your share (1,000 LP are locked forever as minimum liquidity).",
    collectBody: (growth: string, lp: string) =>
      `Swap fees have grown your position by ${growth} since you deposited. Collecting withdraws ${lp} LP — just that growth — and your deposit stays in the pool earning. If the price has moved, the token mix follows the pool's current ratio.`,
    review: "Review",
    signAdd: "Sign and add",
    signRemove: "Sign and remove",
    signCollect: "Sign and collect",
    signCreate: "Sign and create",
    signing: "Signing…",
    exceeds: (s: string) => `Exceeds your ${s} balance`,
    lpExceeds: "Exceeds your LP balance",
    differentTokens: "Choose two different tokens",
    poolExists: (id: string) => `Pool ${id} already exists — add liquidity to it instead.`,
  },
  detail: {
    eyebrow: "Trade / Pool",
    back: "All pools",
    poolId: (id: string) => `Pool ID ${id}`,
    notFoundTitle: "Pool not found",
    notFoundBody: (id: string) => `This network has no pool “${id}”.`,
    error: "Couldn't load this pool from the node.",
    totalSwaps: "Total swaps",
    swaps24h: "24h swaps",
    chart: "Price",
    line: "Line",
    candles: "Candles",
    per: (a: string, b: string) => `${a} per ${b}`,
    noPrices: "No price history yet. Swaps build the chart.",
    history: "Transactions",
    noEvents: "No transactions yet",
    by: "By",
    block: "Block",
    time: "Time",
    event: "Event",
    swapPair: "Swap this pair",
    position: "Your position",
    ev: {
      swap: (a: string, ti: string, b: string, to: string) => `Swap ${a} ${ti} → ${b} ${to}`,
      add: (a: string, ta: string, b: string, tb: string) => `Add ${a} ${ta} + ${b} ${tb}`,
      remove: (lp: string) => `Remove ${lp} LP`,
      create: "Pool created",
    },
  },
  buy: {
    eyebrow: "Trade / Buy",
    title: "Buy XRGE",
    intro: "XRGE trades on Base (Aerodrome). Buy it there with ETH or USDC, then bridge it to RougeChain.",
    contractLabel: "XRGE on Base · official contract",
    contractNote: "Always check the contract address before you trade. Verify it on",
    howTitle: "How to buy",
    steps: [
      "Get ETH or USDC on Base (bridge from Ethereum, or withdraw from an exchange that supports Base).",
      "Open Aerodrome and swap ETH or USDC for XRGE using the contract address above.",
      "Keep XRGE on Base, or bridge it to RougeChain from the Bridge page.",
      "On RougeChain, swap XRGE for other tokens here or provide liquidity to earn fees.",
    ],
    openAerodrome: "Buy on Aerodrome",
    bridge: "Bridge XRGE to RougeChain",
    swapOnChain: "Swap on RougeChain",
    disclaimer: "Trading is at your own risk. Prices move; only trade what you can afford to lose. RougeChain doesn't operate Aerodrome.",
    copy: "Copy contract address",
  },
  toasts: {
    swapped: (a: string, ti: string, b: string, to: string) => `Swap submitted: ${a} ${ti} → ~${b} ${to}`,
    swapFailed: "Swap failed",
    created: (id: string) => `Pool created${id ? `: ${id}` : ""}`,
    createFailed: "Couldn't create the pool",
    added: "Liquidity added",
    addFailed: "Couldn't add liquidity",
    removed: "Liquidity removed",
    removeFailed: "Couldn't remove liquidity",
    collected: "Fees collected",
    collectedBody: (a: string, b: string) => `${a} + ${b} sent to your wallet`,
    collectFailed: "Couldn't collect fees",
  },
  errors: {
    invalidAmount: "Enter a valid amount",
    wholeUnits: (s: string) => `${s} amounts must be whole numbers`,
    tooManyDecimals: (s: string, d: number) => `${s} supports at most ${d} decimal places`,
    tooLarge: "Amount is too large",
    node: "The node returned an error",
  },
} as const;
