/**
 * User-facing English strings for Messenger and Mail. Kept in one place (and in the same key
 * layout as apps/web's `chat.*` / `messenger.*` / `visual.empty.mail.*` i18n keys where they
 * exist) so a translation layer can be added later without touching components.
 */

type Vars = Record<string, string | number>;

/** `{{name}}` interpolation, as i18next does. */
export function fmt(template: string, vars: Vars = {}): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, k: string) => (k in vars ? String(vars[k]) : ""));
}

/** One / other plural pick (English). */
export function plural(count: number, one: string, other: string, vars: Vars = {}): string {
  return fmt(count === 1 ? one : other, { count, ...vars });
}

export const S = {
  common: {
    anonymous: "Anonymous",
    cancel: "Cancel",
    close: "Close",
    you: "You",
    unknown: "Unknown",
    loading: "Loading…",
    copy: "Copy",
    copied: "Copied",
    back: "Back",
    retry: "Retry",
    save: "Save",
    later: "Later",
  },
  gate: {
    title: "Messenger",
    mailTitle: "Mail",
    noWallet: "Create or connect a wallet to start messaging.",
    noWalletMail: "Create or connect a wallet to use RougeChain Mail.",
    openWallet: "Open wallet",
    locked: "{{name}} is locked",
    lockedGeneric: "Your wallet is locked",
    lockedHint: "Unlock to read and send encrypted messages.",
    resolving: "Preparing your messaging identity…",
    resolveFailed: "Couldn't prepare your messaging identity.",
    extensionNote:
      "Extension wallet: messages are signed with a messaging key kept on this device. Export it from the menu to use it in another browser.",
    testnet: "Testnet",
    mainnet: "Mainnet",
  },
  list: {
    title: "Conversations",
    deleteConfirm: "Move this conversation to the trash? It can be restored for 30 days.",
    deleted: "Conversation deleted",
    deleteFailed: "Failed to delete conversation",
    delete: "Delete conversation",
    emptyTitle: "No conversations yet",
    emptyHint: "Start a new chat to begin messaging",
    e2e: "End-to-end encrypted",
    noteToSelf: "Note to Self",
    loadFailed: "Couldn't load conversations. Retrying…",
    search: "Search chats",
  },
  header: {
    newChat: "New chat",
    newGroup: "Group",
    more: "More actions",
    copyAddress: "Copy address",
    addressCopied: "Address copied",
    live: "Live",
    polling: "Polling",
    reregister: "Re-register wallet",
    regenerate: "Regenerate keys",
    exportId: "Export messaging ID",
    importId: "Import messaging ID",
    blocked: "Blocked wallets",
    privacy: "Privacy settings",
    backup: "Back up wallet",
    swap: "Quick swap",
    notifOn: "Mute notifications",
    notifOff: "Enable notifications",
    notifEnabled: "Notifications enabled",
    notifMuted: "Notifications muted",
    registered: "Wallet registered",
    registeredHint: "Your wallet is now visible to other users",
    registerFailed: "Registration failed",
    hidden: "You are hidden — enable “Discoverable” in Privacy settings to register",
    regenConfirm:
      "Regenerate your ML-KEM-768 encryption keys? Your address stays the same, but messages encrypted to the old key become unreadable.",
    regenDone: "Encryption keys regenerated",
    regenFailed: "Key regeneration failed",
    regenExtension: "Extension wallets keep their keys in the extension.",
    exported: "Messaging identity exported — keep this file safe, it holds private keys.",
    imported: "Now messaging as “{{name}}”",
    importFailed: "Import failed",
    noIdentity: "No messaging identity yet",
  },
  empty: {
    selectTitle: "Select a conversation",
    selectHint: "Or start a new chat with quantum-safe encryption",
  },
  namePrompt: {
    title: "Set your display name",
    hint: "Choose a name so other users can recognize you in conversations.",
    placeholder: "Your name",
    saved: "Name set to “{{name}}”",
    savedLocal: "Name saved locally as “{{name}}”",
  },
  chat: {
    placeholder: "Type a message…",
    replyPlaceholder: "Type your reply…",
    captionPlaceholder: "Add a caption (optional)…",
    send: "Send",
    sendReply: "Send reply",
    attach: "Attach image or video",
    pay: "Send payment",
    request: "Request payment",
    encrypting: "Encrypting with ML-KEM-768…",
    decrypting: "Decrypting…",
    startTitle: "Start the conversation",
    startHint: "Messages are end-to-end encrypted",
    noMatchTitle: "No messages match",
    noMatchHint: "Try a different search",
    searchPlaceholder: "Search messages…",
    results_one: "{{count}} result",
    results_other: "{{count}} results",
    selfDestruct: "Self-destruct",
    selfDestructOn: "Self-destruct ({{s}}s)",
    spoiler: "Spoiler",
    spoilerOn: "Spoiler (hidden until tapped)",
    options: "Options",
    reveal: "Tap to reveal",
    tapDetails: "Details",
    unableToDecrypt: "[Unable to decrypt]",
    cryptoLabel: "ML-KEM-768 + ML-DSA-65",
    sendFailed: "Message failed to send",
    noKey: "Cannot send: the recipient's encryption key isn't available. Ask them to re-register their wallet.",
    tooLarge: "File too large. Maximum size is {{mb}} MB.",
    onlyMedia: "Only images and videos are supported.",
    mediaFailed: "Failed to process media.",
    keyChanged: "Key changed",
    keyChangedHint: "This contact's keys changed since you first talked",
    fingerprint: "Fingerprint: {{fp}}",
    recipientCopied: "Recipient address copied",
    deleted: "Message deleted",
    deleteFailed: "Failed to delete message",
    deleteConfirm: "Delete this message? This cannot be undone.",
    reply: "Reply",
    react: "React",
    lightbox: "Full-size image",
    nickname: "Set nickname",
    nicknamePrompt: "Nickname for {{name}} (only on this device; empty to clear):",
    nicknameSaved: "Nickname saved",
    ai: "AI",
    botFailed: "The bot couldn't reply",
  },
  details: {
    title: "Encryption details",
    subtitle: "ML-KEM-768 + AES-256-GCM",
    messageId: "Message ID",
    timestamp: "Timestamp",
    kem: "KEM ciphertext",
    kemHint: "ML-KEM-768 encapsulated shared secret (FIPS 203)",
    iv: "Initialization vector",
    ivHint: "Random nonce for AES-256-GCM encryption",
    content: "Encrypted content",
    contentHint: "AES-256-GCM ciphertext with authentication tag",
    raw: "Raw encrypted package",
    group: "Group package (v2 wrapped keys) · {{count}} recipients",
    signature: "Digital signature",
    signatureHint: "ML-DSA-65 digital signature (FIPS 204) — proves sender authenticity",
    valid: "Valid",
    invalid: "Invalid",
    plaintext: "Decrypted plaintext",
    delete: "Delete message",
    bytes: "{{n}} bytes",
  },
  menu: {
    title: "Conversation options",
    search: "Search messages",
  },
  group: {
    new: "New group",
    newShort: "Group",
    newHint: "Encrypted group chat with 2+ people",
    info: "Group info",
    name: "Group name",
    namePlaceholder: "Group name (optional)",
    members: "Members",
    selected_one: "{{count}} selected",
    selected_other: "{{count}} selected",
    searchContacts: "Search contacts",
    pickTwo: "Pick at least 2 people.",
    noContacts: "No contacts found.",
    noOneToAdd: "No one else in the directory to add.",
    create_one: "Create group ({{count}})",
    create_other: "Create group ({{count}})",
    creating: "Creating…",
    created: "Group created",
    createFailed: "Could not create the group",
    maxMembers: "A group can have at most {{max}} members.",
    untitled_one: "Group ({{count}})",
    untitled_other: "Group ({{count}})",
    memberCount_one: "{{count}} member",
    memberCount_other: "{{count}} members",
    rename: "Rename",
    renamed: "Renamed to {{name}}",
    nameCleared: "Group name cleared",
    renameFailed: "Rename failed",
    addMembers: "Add members",
    addHint: "New members only see messages sent after they join.",
    addCount_one: "Add {{count}}",
    addCount_other: "Add {{count}}",
    added_one: "Added {{count}} member",
    added_other: "Added {{count}} members",
    addFailed: "Could not add members",
    noKeys: "None of the members has an encryption key yet.",
    someKeysMissing_one: "{{count}} member has no encryption key and won't be able to read this.",
    someKeysMissing_other: "{{count}} members have no encryption key and won't be able to read this.",
    e2eNote:
      "Messages are encrypted separately for every member (ML-KEM-768). Leaving or removing members isn't supported by the network yet.",
  },
  requests: {
    primary: "Chats",
    tab: "Requests",
    hint: "People you haven't chatted with. They won't know you've seen their message until you accept.",
    wantsToMessage: "Wants to message you",
    accept: "Accept",
    accepted: "Request accepted",
    delete: "Delete",
    deleteConfirm: "Delete this message request?",
    deleted: "Request deleted",
    deleteFailed: "Could not delete the request",
    banner: "{{name}} wants to message you. Accept to reply and send read receipts.",
  },
  mute: {
    label: "Mute",
    hint: "No sounds or pop-ups for this chat",
    mute: "Mute",
    unmute: "Unmute",
    muted: "Chat muted",
    unmuted: "Chat unmuted",
  },
  block: {
    title: "Blocked wallets",
    block: "Block",
    unblock: "Unblock",
    blockedBadge: "Blocked",
    blocked: "Blocked {{name}}",
    unblocked: "Unblocked {{name}}",
    confirm: "Block {{name}}? Their chats and messages will be hidden on this device.",
    confirmMember: "Block {{name}}? Their messages will be hidden in every chat on this device.",
    emptyTitle: "No one blocked",
    emptyBody: "Wallets you block from a chat or a message request show up here.",
    hint: "Blocking is stored on this device only; the other person isn't told.",
  },
  gif: {
    button: "Send a GIF",
    search: "Search GIFs…",
    none: "No GIFs found",
    unavailable: "GIF service temporarily unavailable",
    powered: "Powered by GIPHY",
  },
  media: {
    image: "Image",
    video: "Video",
    voice: "Voice message",
    loadImage: "Load image from {{host}}",
  },
  receipts: {
    sent: "Sent",
    delivered: "Delivered",
    read: "Read",
    seen: "Seen",
  },
  tip: {
    label: "Tip",
    sent: "You sent a tip",
    received: "Tip received",
  },
  reply: {
    unavailable: "Original message not loaded",
    replyingTo: "Replying to {{name}}",
    cancel: "Cancel reply",
  },
  pay: {
    sendTo: "Send to",
    requestFrom: "Request from",
    amount: "Amount",
    token: "Token",
    memo: "Add a note…",
    balance: "Balance: {{amount}} {{symbol}}",
    fee: "Fee: {{fee}} XRGE · signed with ML-DSA-65",
    feeExtension: "Fee: {{fee}} XRGE · approve in your wallet extension",
    send: "Send {{amount}} {{symbol}}",
    sending: "Sending…",
    request: "Request {{amount}} {{symbol}}",
    sent: "Sent {{amount}} {{symbol}} to {{name}}",
    failed: "Payment failed",
    youSent: "You sent",
    received: "Received",
    confirmed: "Confirmed",
    sentLabel: "Sent",
    youRequested: "You requested",
    requested: "Requested",
    payNow: "Pay {{amount}} {{symbol}}",
    requestLabel: "Payment request",
    modeSend: "Send",
    modeRequest: "Request",
    noSigner: "Unlock your wallet to send a payment.",
  },
  contacts: {
    title: "Start new chat",
    bot: "Quantum Bot",
    botHint: "Chat with an AI assistant over encrypted messaging",
    noteHint: "Save private notes and reminders",
    addByAddress: "Add by rouge1 address or public key",
    manualTitle: "Add contact manually",
    addressLabel: "RougeChain address or public key",
    addressPlaceholder: "rouge1… or paste public key",
    found: "Wallet found on network",
    notRegistered: "Wallet not registered yet. They need to open Messenger first.",
    notFound: "Wallet not found on network",
    self: "Cannot chat with yourself",
    tooShort: "Public key too short",
    enterAddress: "Enter a rouge1… address or public key",
    start: "Start chat",
    creating: "Creating chat…",
    none: "No other users registered yet",
    noneHint: "Add a contact manually above",
    search: "Search the directory",
    failed: "Failed to start conversation",
  },
  privacy: {
    title: "Privacy & security",
    displayName: "Display name",
    profileSaved: "Profile updated",
    profileFailed: "Failed to update profile",
    discoverable: "Discoverable",
    discoverableHint: "Show your wallet in the messenger directory so people can find you",
    storeSent: "Keep sent messages readable",
    storeSentHint: "Stores the plaintext of messages you send on this device",
    storeOn: "Sent message storage enabled",
    storeOff: "Sent message storage disabled",
    clearSent: "Clear stored sent messages",
    cleared: "Stored messages cleared",
    notifications: "Notifications",
    notificationsHint: "Sound and desktop alerts for new messages",
    sound: "Sound",
  },
} as const;

export const MAIL = {
  compose: "Compose",
  refresh: "Refresh",
  settings: "Mail settings",
  claim: "Claim your @rouge.quant / @qwalla.mail address",
  claimHint:
    "Claim a name to receive mail by name instead of wallet ID. One name gives you both addresses: @{{a}} and @{{b}}.",
  inbox: "Inbox",
  sent: "Sent",
  trash: "Trash",
  to: "To",
  toPlaceholder: "alice@{{a}}, alice@{{b}} or wallet ID",
  subject: "Subject",
  message: "Message",
  messagePlaceholder: "Write your message…",
  resolving: "Resolving…",
  resolved: "Resolved: {{id}}…",
  unresolved: "Could not resolve “{{to}}”. Use a @{{a}} / @{{b}} address or wallet ID.",
  attach: "Attach file",
  attachHint: "Max 2 MB · encrypted with ML-KEM",
  attachTooLarge: "Attachment too large (max 2 MB)",
  removeAttachment: "Remove attachment",
  send: "Send mail",
  sending: "Sending…",
  sentToast: "Mail sent!",
  sendFailed: "Failed to send",
  from: "from: {{addr}}",
  noSubject: "(No subject)",
  thread_one: "{{count}} message in thread",
  thread_other: "{{count}} messages in thread",
  restore: "Restore to inbox",
  restored: "Restored to inbox",
  toTrash: "Move to trash",
  moved: "Moved to trash",
  deleteForever: "Delete permanently",
  deletedForever: "Mail deleted permanently",
  actionFailed: "Action failed",
  reply: "Reply",
  download: "Download",
  collapse: "collapse",
  e2e: "ML-KEM-768 + ML-DSA-65 encrypted",
  sigValid: "Signature verified (ML-DSA-65)",
  sigInvalid: "Signature invalid — this mail may be forged",
  sigUnknown: "Signature not verified (sender key unknown)",
  signature: "Email signature",
  signatureHint: "Your signature is automatically appended to new emails and replies.",
  signaturePlaceholder: "Best regards,\nYour Name\nyou@rouge.quant",
  preview: "Preview:",
  on: "On",
  off: "Off",
  saveSettings: "Save settings",
  settingsSaved: "Settings saved",
  loadFailed: "Couldn't load mail. Retrying…",
  empty: {
    inboxTitle: "Inbox zero",
    sentTitle: "Nothing sent yet",
    trashTitle: "Trash is empty",
    inboxNamed: "Your addresses: {{a}} · {{b}}",
    inboxClaim: "Claim a name to get your @{{a}} and @{{b}} addresses",
    sentHint: "Mail you send will show up here.",
    trashHint: "Deleted mail lands here.",
  },
} as const;
