/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BridgeVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "EMERGENCY_TIMELOCK"
      | "cancelEmergencyWithdraw"
      | "deposit"
      | "depositNonce"
      | "emergencyWithdraw"
      | "emergencyWithdrawRequested"
      | "emergencyWithdrawRequestedAt"
      | "owner"
      | "processedL1Txs"
      | "release"
      | "renounceOwnership"
      | "requestEmergencyWithdraw"
      | "totalLocked"
      | "transferOwnership"
      | "vaultBalance"
      | "xrgeToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BridgeDeposit"
      | "BridgeRelease"
      | "EmergencyWithdraw"
      | "EmergencyWithdrawCancelled"
      | "EmergencyWithdrawRequested"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "EMERGENCY_TIMELOCK",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelEmergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "depositNonce",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdrawRequested",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdrawRequestedAt",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processedL1Txs",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "release",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestEmergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalLocked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "xrgeToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "EMERGENCY_TIMELOCK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelEmergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdrawRequested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdrawRequestedAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processedL1Txs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestEmergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "xrgeToken", data: BytesLike): Result;
}

export namespace BridgeDepositEvent {
  export type InputTuple = [
    sender: AddressLike,
    amount: BigNumberish,
    rougechainPubkey: string,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    amount: bigint,
    rougechainPubkey: string,
    nonce: bigint
  ];
  export interface OutputObject {
    sender: string;
    amount: bigint;
    rougechainPubkey: string;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BridgeReleaseEvent {
  export type InputTuple = [
    recipient: AddressLike,
    amount: BigNumberish,
    l1TxId: string
  ];
  export type OutputTuple = [recipient: string, amount: bigint, l1TxId: string];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
    l1TxId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawCancelledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawRequestedEvent {
  export type InputTuple = [executeAfter: BigNumberish];
  export type OutputTuple = [executeAfter: bigint];
  export interface OutputObject {
    executeAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BridgeVault extends BaseContract {
  connect(runner?: ContractRunner | null): BridgeVault;
  waitForDeployment(): Promise<this>;

  interface: BridgeVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  EMERGENCY_TIMELOCK: TypedContractMethod<[], [bigint], "view">;

  cancelEmergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  deposit: TypedContractMethod<
    [amount: BigNumberish, rougechainPubkey: string],
    [void],
    "nonpayable"
  >;

  depositNonce: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  emergencyWithdrawRequested: TypedContractMethod<[], [boolean], "view">;

  emergencyWithdrawRequestedAt: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  processedL1Txs: TypedContractMethod<[arg0: string], [boolean], "view">;

  release: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, l1TxId: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestEmergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  totalLocked: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vaultBalance: TypedContractMethod<[], [bigint], "view">;

  xrgeToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "EMERGENCY_TIMELOCK"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelEmergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [amount: BigNumberish, rougechainPubkey: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositNonce"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdrawRequested"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdrawRequestedAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processedL1Txs"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, l1TxId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestEmergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalLocked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vaultBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "xrgeToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BridgeDeposit"
  ): TypedContractEvent<
    BridgeDepositEvent.InputTuple,
    BridgeDepositEvent.OutputTuple,
    BridgeDepositEvent.OutputObject
  >;
  getEvent(
    key: "BridgeRelease"
  ): TypedContractEvent<
    BridgeReleaseEvent.InputTuple,
    BridgeReleaseEvent.OutputTuple,
    BridgeReleaseEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdraw"
  ): TypedContractEvent<
    EmergencyWithdrawEvent.InputTuple,
    EmergencyWithdrawEvent.OutputTuple,
    EmergencyWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawCancelled"
  ): TypedContractEvent<
    EmergencyWithdrawCancelledEvent.InputTuple,
    EmergencyWithdrawCancelledEvent.OutputTuple,
    EmergencyWithdrawCancelledEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawRequested"
  ): TypedContractEvent<
    EmergencyWithdrawRequestedEvent.InputTuple,
    EmergencyWithdrawRequestedEvent.OutputTuple,
    EmergencyWithdrawRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BridgeDeposit(address,uint256,string,uint256)": TypedContractEvent<
      BridgeDepositEvent.InputTuple,
      BridgeDepositEvent.OutputTuple,
      BridgeDepositEvent.OutputObject
    >;
    BridgeDeposit: TypedContractEvent<
      BridgeDepositEvent.InputTuple,
      BridgeDepositEvent.OutputTuple,
      BridgeDepositEvent.OutputObject
    >;

    "BridgeRelease(address,uint256,string)": TypedContractEvent<
      BridgeReleaseEvent.InputTuple,
      BridgeReleaseEvent.OutputTuple,
      BridgeReleaseEvent.OutputObject
    >;
    BridgeRelease: TypedContractEvent<
      BridgeReleaseEvent.InputTuple,
      BridgeReleaseEvent.OutputTuple,
      BridgeReleaseEvent.OutputObject
    >;

    "EmergencyWithdraw(address,uint256)": TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;
    EmergencyWithdraw: TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;

    "EmergencyWithdrawCancelled()": TypedContractEvent<
      EmergencyWithdrawCancelledEvent.InputTuple,
      EmergencyWithdrawCancelledEvent.OutputTuple,
      EmergencyWithdrawCancelledEvent.OutputObject
    >;
    EmergencyWithdrawCancelled: TypedContractEvent<
      EmergencyWithdrawCancelledEvent.InputTuple,
      EmergencyWithdrawCancelledEvent.OutputTuple,
      EmergencyWithdrawCancelledEvent.OutputObject
    >;

    "EmergencyWithdrawRequested(uint256)": TypedContractEvent<
      EmergencyWithdrawRequestedEvent.InputTuple,
      EmergencyWithdrawRequestedEvent.OutputTuple,
      EmergencyWithdrawRequestedEvent.OutputObject
    >;
    EmergencyWithdrawRequested: TypedContractEvent<
      EmergencyWithdrawRequestedEvent.InputTuple,
      EmergencyWithdrawRequestedEvent.OutputTuple,
      EmergencyWithdrawRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
