/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BridgeVault } from "./BridgeVault";
export type { RougeBridge } from "./RougeBridge";
export type { TestXRGE } from "./TestXRGE";
