/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RougeBridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelTimelock"
      | "depositERC20"
      | "depositETH"
      | "emergencyWithdrawERC20"
      | "emergencyWithdrawETH"
      | "executeTimelock"
      | "getTimelockQueueLength"
      | "guardian"
      | "largeWithdrawalThreshold"
      | "owner"
      | "pause"
      | "paused"
      | "processedL1Txs"
      | "releaseERC20"
      | "releaseETH"
      | "renounceOwnership"
      | "setGuardian"
      | "setLargeWithdrawalThreshold"
      | "setSupportedToken"
      | "setTimelockDuration"
      | "supportedTokens"
      | "timelockDuration"
      | "timelockQueue"
      | "transferOwnership"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BridgeDepositERC20"
      | "BridgeDepositETH"
      | "BridgeReleaseERC20"
      | "BridgeReleaseETH"
      | "GuardianUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "ThresholdUpdated"
      | "TimelockCancelled"
      | "TimelockExecuted"
      | "TimelockQueued"
      | "TokenSupported"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelTimelock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositERC20",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "depositETH", values: [string]): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdrawERC20",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdrawETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeTimelock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTimelockQueueLength",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "guardian", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "largeWithdrawalThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processedL1Txs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseERC20",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseETH",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGuardian",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLargeWithdrawalThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSupportedToken",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTimelockDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "timelockDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "timelockQueue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "cancelTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdrawERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdrawETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimelockQueueLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "guardian", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "largeWithdrawalThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processedL1Txs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "releaseETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLargeWithdrawalThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTimelockDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timelockDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timelockQueue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace BridgeDepositERC20Event {
  export type InputTuple = [
    sender: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    rougechainPubkey: string
  ];
  export type OutputTuple = [
    sender: string,
    token: string,
    amount: bigint,
    rougechainPubkey: string
  ];
  export interface OutputObject {
    sender: string;
    token: string;
    amount: bigint;
    rougechainPubkey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BridgeDepositETHEvent {
  export type InputTuple = [
    sender: AddressLike,
    amount: BigNumberish,
    rougechainPubkey: string
  ];
  export type OutputTuple = [
    sender: string,
    amount: bigint,
    rougechainPubkey: string
  ];
  export interface OutputObject {
    sender: string;
    amount: bigint;
    rougechainPubkey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BridgeReleaseERC20Event {
  export type InputTuple = [
    recipient: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    l1TxId: BytesLike
  ];
  export type OutputTuple = [
    recipient: string,
    token: string,
    amount: bigint,
    l1TxId: string
  ];
  export interface OutputObject {
    recipient: string;
    token: string;
    amount: bigint;
    l1TxId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BridgeReleaseETHEvent {
  export type InputTuple = [
    recipient: AddressLike,
    amount: BigNumberish,
    l1TxId: BytesLike
  ];
  export type OutputTuple = [recipient: string, amount: bigint, l1TxId: string];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
    l1TxId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GuardianUpdatedEvent {
  export type InputTuple = [oldGuardian: AddressLike, newGuardian: AddressLike];
  export type OutputTuple = [oldGuardian: string, newGuardian: string];
  export interface OutputObject {
    oldGuardian: string;
    newGuardian: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdUpdatedEvent {
  export type InputTuple = [
    oldThreshold: BigNumberish,
    newThreshold: BigNumberish
  ];
  export type OutputTuple = [oldThreshold: bigint, newThreshold: bigint];
  export interface OutputObject {
    oldThreshold: bigint;
    newThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockCancelledEvent {
  export type InputTuple = [requestId: BigNumberish];
  export type OutputTuple = [requestId: bigint];
  export interface OutputObject {
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockExecutedEvent {
  export type InputTuple = [requestId: BigNumberish];
  export type OutputTuple = [requestId: bigint];
  export interface OutputObject {
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockQueuedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    executeAfter: BigNumberish
  ];
  export type OutputTuple = [requestId: bigint, executeAfter: bigint];
  export interface OutputObject {
    requestId: bigint;
    executeAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenSupportedEvent {
  export type InputTuple = [token: AddressLike, supported: boolean];
  export type OutputTuple = [token: string, supported: boolean];
  export interface OutputObject {
    token: string;
    supported: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RougeBridge extends BaseContract {
  connect(runner?: ContractRunner | null): RougeBridge;
  waitForDeployment(): Promise<this>;

  interface: RougeBridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelTimelock: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositERC20: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, rougechainPubkey: string],
    [void],
    "nonpayable"
  >;

  depositETH: TypedContractMethod<
    [rougechainPubkey: string],
    [void],
    "payable"
  >;

  emergencyWithdrawERC20: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  emergencyWithdrawETH: TypedContractMethod<[], [void], "nonpayable">;

  executeTimelock: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getTimelockQueueLength: TypedContractMethod<[], [bigint], "view">;

  guardian: TypedContractMethod<[], [string], "view">;

  largeWithdrawalThreshold: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  processedL1Txs: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  releaseERC20: TypedContractMethod<
    [
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      l1TxId: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  releaseETH: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, l1TxId: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setGuardian: TypedContractMethod<
    [newGuardian: AddressLike],
    [void],
    "nonpayable"
  >;

  setLargeWithdrawalThreshold: TypedContractMethod<
    [newThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSupportedToken: TypedContractMethod<
    [token: AddressLike, supported: boolean],
    [void],
    "nonpayable"
  >;

  setTimelockDuration: TypedContractMethod<
    [newDuration: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportedTokens: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  timelockDuration: TypedContractMethod<[], [bigint], "view">;

  timelockQueue: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, bigint, boolean, boolean] & {
        token: string;
        to: string;
        amount: bigint;
        l1TxId: string;
        executeAfter: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelTimelock"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositERC20"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, rougechainPubkey: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositETH"
  ): TypedContractMethod<[rougechainPubkey: string], [void], "payable">;
  getFunction(
    nameOrSignature: "emergencyWithdrawERC20"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdrawETH"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeTimelock"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getTimelockQueueLength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "guardian"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "largeWithdrawalThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "processedL1Txs"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "releaseERC20"
  ): TypedContractMethod<
    [
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      l1TxId: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releaseETH"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, l1TxId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGuardian"
  ): TypedContractMethod<[newGuardian: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLargeWithdrawalThreshold"
  ): TypedContractMethod<[newThreshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSupportedToken"
  ): TypedContractMethod<
    [token: AddressLike, supported: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTimelockDuration"
  ): TypedContractMethod<[newDuration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportedTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "timelockDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "timelockQueue"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, bigint, boolean, boolean] & {
        token: string;
        to: string;
        amount: bigint;
        l1TxId: string;
        executeAfter: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "BridgeDepositERC20"
  ): TypedContractEvent<
    BridgeDepositERC20Event.InputTuple,
    BridgeDepositERC20Event.OutputTuple,
    BridgeDepositERC20Event.OutputObject
  >;
  getEvent(
    key: "BridgeDepositETH"
  ): TypedContractEvent<
    BridgeDepositETHEvent.InputTuple,
    BridgeDepositETHEvent.OutputTuple,
    BridgeDepositETHEvent.OutputObject
  >;
  getEvent(
    key: "BridgeReleaseERC20"
  ): TypedContractEvent<
    BridgeReleaseERC20Event.InputTuple,
    BridgeReleaseERC20Event.OutputTuple,
    BridgeReleaseERC20Event.OutputObject
  >;
  getEvent(
    key: "BridgeReleaseETH"
  ): TypedContractEvent<
    BridgeReleaseETHEvent.InputTuple,
    BridgeReleaseETHEvent.OutputTuple,
    BridgeReleaseETHEvent.OutputObject
  >;
  getEvent(
    key: "GuardianUpdated"
  ): TypedContractEvent<
    GuardianUpdatedEvent.InputTuple,
    GuardianUpdatedEvent.OutputTuple,
    GuardianUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdUpdated"
  ): TypedContractEvent<
    ThresholdUpdatedEvent.InputTuple,
    ThresholdUpdatedEvent.OutputTuple,
    ThresholdUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TimelockCancelled"
  ): TypedContractEvent<
    TimelockCancelledEvent.InputTuple,
    TimelockCancelledEvent.OutputTuple,
    TimelockCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TimelockExecuted"
  ): TypedContractEvent<
    TimelockExecutedEvent.InputTuple,
    TimelockExecutedEvent.OutputTuple,
    TimelockExecutedEvent.OutputObject
  >;
  getEvent(
    key: "TimelockQueued"
  ): TypedContractEvent<
    TimelockQueuedEvent.InputTuple,
    TimelockQueuedEvent.OutputTuple,
    TimelockQueuedEvent.OutputObject
  >;
  getEvent(
    key: "TokenSupported"
  ): TypedContractEvent<
    TokenSupportedEvent.InputTuple,
    TokenSupportedEvent.OutputTuple,
    TokenSupportedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BridgeDepositERC20(address,address,uint256,string)": TypedContractEvent<
      BridgeDepositERC20Event.InputTuple,
      BridgeDepositERC20Event.OutputTuple,
      BridgeDepositERC20Event.OutputObject
    >;
    BridgeDepositERC20: TypedContractEvent<
      BridgeDepositERC20Event.InputTuple,
      BridgeDepositERC20Event.OutputTuple,
      BridgeDepositERC20Event.OutputObject
    >;

    "BridgeDepositETH(address,uint256,string)": TypedContractEvent<
      BridgeDepositETHEvent.InputTuple,
      BridgeDepositETHEvent.OutputTuple,
      BridgeDepositETHEvent.OutputObject
    >;
    BridgeDepositETH: TypedContractEvent<
      BridgeDepositETHEvent.InputTuple,
      BridgeDepositETHEvent.OutputTuple,
      BridgeDepositETHEvent.OutputObject
    >;

    "BridgeReleaseERC20(address,address,uint256,bytes32)": TypedContractEvent<
      BridgeReleaseERC20Event.InputTuple,
      BridgeReleaseERC20Event.OutputTuple,
      BridgeReleaseERC20Event.OutputObject
    >;
    BridgeReleaseERC20: TypedContractEvent<
      BridgeReleaseERC20Event.InputTuple,
      BridgeReleaseERC20Event.OutputTuple,
      BridgeReleaseERC20Event.OutputObject
    >;

    "BridgeReleaseETH(address,uint256,bytes32)": TypedContractEvent<
      BridgeReleaseETHEvent.InputTuple,
      BridgeReleaseETHEvent.OutputTuple,
      BridgeReleaseETHEvent.OutputObject
    >;
    BridgeReleaseETH: TypedContractEvent<
      BridgeReleaseETHEvent.InputTuple,
      BridgeReleaseETHEvent.OutputTuple,
      BridgeReleaseETHEvent.OutputObject
    >;

    "GuardianUpdated(address,address)": TypedContractEvent<
      GuardianUpdatedEvent.InputTuple,
      GuardianUpdatedEvent.OutputTuple,
      GuardianUpdatedEvent.OutputObject
    >;
    GuardianUpdated: TypedContractEvent<
      GuardianUpdatedEvent.InputTuple,
      GuardianUpdatedEvent.OutputTuple,
      GuardianUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ThresholdUpdated(uint256,uint256)": TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;
    ThresholdUpdated: TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;

    "TimelockCancelled(uint256)": TypedContractEvent<
      TimelockCancelledEvent.InputTuple,
      TimelockCancelledEvent.OutputTuple,
      TimelockCancelledEvent.OutputObject
    >;
    TimelockCancelled: TypedContractEvent<
      TimelockCancelledEvent.InputTuple,
      TimelockCancelledEvent.OutputTuple,
      TimelockCancelledEvent.OutputObject
    >;

    "TimelockExecuted(uint256)": TypedContractEvent<
      TimelockExecutedEvent.InputTuple,
      TimelockExecutedEvent.OutputTuple,
      TimelockExecutedEvent.OutputObject
    >;
    TimelockExecuted: TypedContractEvent<
      TimelockExecutedEvent.InputTuple,
      TimelockExecutedEvent.OutputTuple,
      TimelockExecutedEvent.OutputObject
    >;

    "TimelockQueued(uint256,uint256)": TypedContractEvent<
      TimelockQueuedEvent.InputTuple,
      TimelockQueuedEvent.OutputTuple,
      TimelockQueuedEvent.OutputObject
    >;
    TimelockQueued: TypedContractEvent<
      TimelockQueuedEvent.InputTuple,
      TimelockQueuedEvent.OutputTuple,
      TimelockQueuedEvent.OutputObject
    >;

    "TokenSupported(address,bool)": TypedContractEvent<
      TokenSupportedEvent.InputTuple,
      TokenSupportedEvent.OutputTuple,
      TokenSupportedEvent.OutputObject
    >;
    TokenSupported: TypedContractEvent<
      TokenSupportedEvent.InputTuple,
      TokenSupportedEvent.OutputTuple,
      TokenSupportedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
