/**
 * Bridge user-facing strings (English). Kept in one place so i18n can be added later; wording
 * follows apps/web's `bridge.*` / `base.*` locale keys where the flow is the same.
 */
type Vars = Record<string, string | number>;

/** Tiny `{{name}}` interpolation (same placeholder syntax as apps/web's i18next strings). */
export function fmt(template: string, vars: Vars = {}): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, k: string) => (k in vars ? String(vars[k]) : `{{${k}}}`));
}

export const S = {
  eyebrow: "Cross-chain",
  title: "Bridge",
  subtitle: "Move assets between Base, Bitcoin and RougeChain.",
  loading: "Loading bridge configuration…",
  notEnabled: "The bridge is not enabled on this node.",
  configError: "Couldn't reach the node's bridge configuration. Check your connection and try again.",
  retry: "Try again",
  processing: "Processing…",
  asset: "Asset",
  tabs: { deposit: "Deposit", withdraw: "Withdraw" },
  networkBadge: { mainnet: "Mainnet", testnet: "Testnet" },

  networkUnknown: {
    title: "Network not confirmed",
    body: "This node didn't report a recognized Base chain, so the bridge can't tell whether you're on Base mainnet or a testnet. Bridging is disabled here to protect your funds. Check the node's bridge config (chainId in /bridge/config) and reload.",
  },
  networkMismatch: {
    title: "Network mismatch — bridge disabled",
    body: "You're on the RougeChain {{network}} network, but this node's bridge reports {{chainLabel}} (chain {{chainId}}). A {{network}} network must not bridge {{assets}}, so bridging is disabled to protect your funds. This is a node misconfiguration — its bridge chainId/token must match the {{network}} Base chain.",
    realMainnetAssets: "real mainnet assets",
    testnetAssets: "testnet assets",
  },

  wallet: {
    none: "Create or import a RougeChain wallet to bridge. Deposits are credited to it and withdrawals are signed by it.",
    open: "Open wallet",
    locked: "Your wallet is locked. Unlock it to bridge.",
    extension: "Connected through the RougeChain extension — it will ask you to approve each withdrawal.",
    receivingWallet: "Receiving RougeChain wallet",
  },

  form: {
    from: "From · {{chain}}",
    to: "To · {{chain}}",
    balance: "Balance: {{balance}}",
    amount: "Amount",
    max: "Max",
    receiveAtBitcoin: "Receive at (Bitcoin address)",
    receiveAtBase: "Receive at (Base address)",
    btcAddressPlaceholder: "bc1… / Bitcoin address",
    btcTestnetAddressPlaceholder: "tb1… / testnet address",
    chooseWallet: "Choose a wallet",
    baseWallet: "Base wallet",
    connectWallet: "Connect {{wallet}} ({{chain}})",
    disconnect: "Disconnect",
    review: "Review",
    back: "Back",
    fee: "Bridge fee",
    feeValue: "0.1 XRGE",
    useMyBaseAddress: "Use my Base address",
    connectedAs: "Connected {{address}}",
    connectedLocal: "RougeChain Base wallet · {{address}}",
    wrongChain: "Your Base wallet is on chain {{actual}}, not {{expected}} ({{chain}}). Switch networks in your wallet, then reconnect.",
    noProvider: "No Base wallet found in this browser. Install one (MetaMask, Coinbase Wallet, the RougeChain extension) or use your RougeChain Base wallet.",
    useLocal: "Use my RougeChain Base wallet",
    useLocalHint: "Your Base address from your recovery phrase — no MetaMask needed. Every transaction asks for your approval.",
  },

  info: {
    depositXrge: "Approve + deposit in two Base wallet transactions. 1:1 conversion.",
    depositEvm: "Send {{asset}} via your Base wallet → auto-claim {{l1}} on RougeChain. 1:1 conversion.",
    withdrawBtc: "Submit withdrawal → the BTC relayer sends Bitcoin to your address. Confirmation time depends on the Bitcoin network.",
    withdrawEvm: "Submit withdrawal → the relayer releases on Base (typically under 2 minutes).",
  },

  review: {
    title: "Review",
    youSend: "You send",
    youReceive: "You receive",
    from: "From",
    to: "To",
    recipient: "Recipient",
    baseWallet: "Base wallet",
    network: "Network",
    fee: "Bridge fee",
    steps: "Wallet steps",
    depositEthSteps: "1 Base transaction (send ETH to the bridge), then 1 signature to claim.",
    depositUsdcSteps: "1 Base transaction (USDC transfer to the bridge), then 1 signature to claim.",
    depositXrgeSteps: "2 Base transactions: approve the vault, then deposit.",
    withdrawLocal: "Signed in this browser with your ML-DSA-65 key. Your key never leaves this page.",
    withdrawExtension: "Your RougeChain extension will ask you to approve this withdrawal.",
    irreversible: "Bridge transfers can't be reversed. Check the amount and address.",
    confirmDeposit: "Confirm and open wallet",
    confirmWithdraw: "Sign and withdraw",
    networkFeeDeducted: "Bitcoin network fee (deducted)",
  },

  btc: {
    connectForAddress: "Unlock or connect your RougeChain wallet to get your Bitcoin deposit address.",
    received: "Received — {{amount}} qBTC credited",
    nowInWallet: "Your qBTC is now in your RougeChain wallet.",
    yourDepositAddress: "Your Bitcoin deposit address",
    fetchingAddress: "Fetching your deposit address…",
    tryAgain: "Try again",
    depositQrAlt: "Bitcoin deposit address QR code",
    depositAddressLabel: "deposit address",
    sendFromAnyWallet: "Send BTC from any wallet — any amount, no memo or tag needed. Your qBTC will appear automatically once the deposit confirms (~30–60 min on Bitcoin).",
    testnetOnly: "Testnet — send testnet BTC only.",
    addressWarmingUp: "Setting up your deposit address, try again in a moment.",
    addressFetchFailed: "Couldn't fetch a deposit address. Try again.",
    watching: "Watching for your deposit…",
    advanced: {
      title: "Advanced: deposit with OP_RETURN",
      intro: "For power users, or to recover a manual deposit already sent with an OP_RETURN binding.",
      step1: "Send BTC to the custody address",
      custodyQrAlt: "Bitcoin custody address QR code",
      custodyAddressLabel: "custody address",
      step2: "Add an OP_RETURN with your RougeChain address",
      step2Help: "In the same transaction, paste this into your wallet's OP_RETURN / memo / data field. It binds the deposit to your wallet — without it the funds can't be credited.",
      rougeAddressLabel: "RougeChain address",
      opReturnWallets: "OP_RETURN is supported by wallets like Sparrow, Electrum, BlueWallet (advanced) and bitcoinjs. Custodial apps (Coinbase, Cash App) usually can't attach one.",
      step3: "Paste the Bitcoin txid to claim qBTC",
      txidLabel: "Bitcoin transaction id",
      txidPlaceholder: "64 hex characters",
      claimButton: "Claim qBTC",
      claimHelp: "Verification waits for Bitcoin confirmations, so this can take a while. Claiming is idempotent — safe to re-paste the same txid later.",
    },
  },

  btcWithdraw: {
    minimum: "Minimum withdrawal",
    networkFee: "Bitcoin network fee (estimate)",
    feeUnavailable: "estimate unavailable",
    youReceive: "You receive ≈",
    feeNote: "Estimated from mempool.space (~{{vbytes}} vB payout). The exact network fee of the payout is deducted from the BTC you receive (max {{max}} BTC).",
    paused: "BTC withdrawals are paused while the Bitcoin payout service is being launched. Your qBTC is safe; deposits and other withdrawals work normally.",
  },

  claim: {
    title: "Claim an existing deposit",
    help: "Sent ETH or USDC to the bridge but it didn't arrive? Paste the Base transaction hash to claim it — mints to your RougeChain wallet. Sign with the Base wallet that sent it. Waits for confirmations automatically.",
    txHashLabel: "Base transaction hash",
    token: "Token sent",
    claiming: "Claiming…",
    button: "Claim deposit",
  },

  activity: {
    title: "Recent bridge activity",
    loading: "Loading activity…",
    empty: "No bridge activity yet",
    emptyHint: "Bridge deposits and withdrawals for this wallet will appear here.",
    bridgedIn: "Bridged in",
    bridgedOut: "Bridged out",
    statusPending: "Pending",
    statusCompleted: "Completed",
    all: "All bridge activity",
    details: "Details",
  },

  pending: {
    title: "Withdrawal release status",
    loading: "Loading withdrawals…",
    failedAttempts: "{{count}} failed attempt(s)",
    viewOnMempool: "View on mempool.space",
    status: { retrying: "Retrying", refunded: "Refunded", released: "Released", pending: "Pending" },
  },

  steps: {
    checkingChain: "Checking your Base wallet network…",
    approvingXrge: "Approving XRGE…",
    waitingApproval: "Waiting for approval confirmation…",
    depositingVault: "Depositing to vault…",
    waitingDeposit: "Waiting for deposit confirmation…",
    waitingBase: "Waiting for Base confirmations…",
    waitingBaseAttempt: "Waiting for Base confirmations… ({{attempt}}/30)",
    waitingBitcoin: "Waiting for Bitcoin confirmations…",
    waitingBitcoinAttempt: "Waiting for Bitcoin confirmations… ({{attempt}}/30)",
    sendingToBridge: "Sending {{symbol}} to the bridge…",
    signingClaim: "Signing claim…",
    signingWithdrawal: "Signing withdrawal…",
    submittingWithdrawal: "Submitting withdrawal…",
  },

  toasts: {
    connected: "Connected to {{chain}}",
    claimed: "Claimed! {{token}} minted to your RougeChain wallet.",
    claimedQbtc: "Claimed! qBTC minted to your RougeChain wallet.",
    btcNotConfirmedYet: "Deposit not confirmed yet — Bitcoin can take a while. Re-paste the txid to claim once it confirms.",
    bridgedXrge: "Bridged {{amount}} XRGE to RougeChain!",
    xrgeArrivesAutomatically: "Deposit confirmed on Base — your XRGE will arrive on RougeChain automatically once it finalizes.",
    bridgedEvm: "Bridged {{amount}} {{from}} → {{to}}!",
    depositSentPending: "Deposit sent — {{token}} arrives once it confirms. If it doesn't, use \"Claim an existing deposit\" with tx {{tx}}…",
    withdrawQueuedBtc: "Withdrawal queued — the BTC relayer will send BTC to your Bitcoin address.",
    withdrawSubmittedXrge: "Withdrawal submitted! The relayer will release XRGE on Base.",
    withdrawSubmittedEvm: "Withdrawal submitted! The relayer will send {{symbol}} to your Base address.",
  },

  errors: {
    networkNotConfirmed: "Network not confirmed — bridge disabled to protect your funds",
    connectFailed: "Failed to connect",
    baseTimeout: "timed out waiting for Base confirmations",
    bitcoinTimeout: "timed out waiting for Bitcoin confirmations",
    invalidBaseTxHash: "Enter a valid Base transaction hash (0x + 64 hex)",
    connectSendingBaseWallet: "Connect the Base wallet that sent the deposit",
    connectRougeToReceive: "Unlock your RougeChain wallet to receive the funds",
    signatureRejected: "Signature rejected — sign with the Base wallet that sent the deposit",
    claimFailed: "Claim failed",
    btcClaimFailed: "BTC claim failed",
    invalidBtcTxid: "Enter a valid Bitcoin transaction id (64 hex characters)",
    connectBaseFirst: "Connect your Base wallet first",
    connectRougeFirst: "Unlock your RougeChain wallet first",
    invalidAmount: "Enter a valid amount",
    tooManyDecimals: "{{symbol}} supports at most {{decimals}} decimal places",
    wholeXrge: "XRGE bridges in whole units — enter a whole number",
    insufficientOnBase: "Insufficient {{symbol}} balance on Base",
    insufficientBalance: "Insufficient {{symbol}} balance",
    insufficientFee: "You need 0.1 XRGE on RougeChain for the bridge fee",
    xrgeNotConfigured: "XRGE bridge not fully configured",
    notConfigured: "Bridge not configured",
    approvalFailed: "The XRGE approval failed or timed out on Base",
    depositTxFailed: "Deposit transaction failed or timed out on Base",
    depositFailed: "Bridge deposit failed",
    invalidBtcAddress: "Enter a valid {{network}} Bitcoin address",
    invalidEvmAddress: "Enter a valid Base address (0x + 40 hex characters)",
    badChecksum: "Address checksum doesn't match — check for typos",
    withdrawFailed: "Withdrawal failed",
    btcBelowMinimum: "Minimum qBTC withdrawal is {{min}} BTC (the Bitcoin network fee is deducted from the payout).",
    wrongChain: "Your Base wallet is on the wrong network (chain {{actual}}); switch to {{chain}} ({{expected}}) and try again.",
    rejected: "Request rejected in your wallet",
  },

  approve: {
    txTitle: "Approve {{chain}} transaction",
    signTitle: "Approve signature request",
    action: "Action",
    to: "To",
    value: "Value",
    fee: "Max network fee",
    message: "Message",
    reject: "Reject",
    approve: "Approve & sign",
    actions: {
      approve: "Allow the bridge to spend your tokens",
      transfer: "Token transfer",
      deposit: "Bridge deposit",
      eth: "Send ETH",
      call: "Contract call",
    } as Record<string, string>,
    mainnetWarning: "This is Base mainnet with real funds. Transactions can't be reversed — check the address.",
    testnetWarning: "Base Sepolia testnet — these tokens have no value.",
    localSign: "Signed locally in your browser with the key derived from your recovery phrase. Nothing secret leaves this page.",
  },
} as const;
