export { RougeChain, tokenMintingActive } from "./client.js";
export type { RougeChainOptions, TrackStats, ArtistStats, SocialComment, SocialPost, PostStats } from "./client.js";

export { Wallet } from "./wallet.js";

export {
  ContractsClient,
  predictContractAddress,
  suggestGasLimit,
  contractCallFee,
  createSignedContractPublish,
  createSignedContractCall,
  bytesToBase64,
  base64ToBytes,
  CONTRACT_MAX_GAS,
  CONTRACT_GAS_PRICE_XRGE,
  CONTRACT_DEPLOY_FEE_XRGE,
  QUANTA_PER_XRGE,
  xrgeToQuanta,
  quantaToXrge,
  normalizeContractAttach,
} from "./contracts.js";
export type { GameContract } from "./contracts.js";

export {
  generateMnemonic,
  validateMnemonic,
  mnemonicToMLDSASeed,
  keypairFromMnemonic,
} from "./mnemonic.js";

export {
  signTransaction,
  verifyTransaction,
  serializePayload,
  createSignedTransfer,
  createSignedTokenCreation,
  createSignedTokenMint,
  tokenMintFields,
  TOKEN_MINT_MAX_AMOUNT,
  TOKEN_MINT_FEE_XRGE,
  TOKEN_CREATE_FEE_XRGE,
  createSignedBridgeWithdraw,
  createSignedTokenMetadataUpdate,
  createSignedTokenMetadataClaim,
  createSignedTokenApproval,
  createSignedTokenTransferFrom,
  createSignedShield,
  createSignedShieldedTransfer,
  createSignedUnshield,
  BURN_ADDRESS,
  isBurnAddress,
  signRequest,
} from "./signer.js";
export type { TokenCreationOptions } from "./signer.js";

export {
  signMessage,
  verifyMessage,
  messageSigningBytes,
  createSignInMessage,
  parseSignInMessage,
  verifySignIn,
  claimedSignInDomain,
  looksLikeTransactionPayload,
  visibleMessageText,
  reviewSignMessageRequest,
  SIGNED_MESSAGE_PREFIX,
  MAX_SIGN_MESSAGE_BYTES,
  SIGN_IN_MIN_NONCE_LENGTH,
  ML_DSA_65_PUBLIC_KEY_BYTES,
  ML_DSA_65_SIGNATURE_BYTES,
} from "./message-signing.js";
export type {
  SignInFields,
  SignInFailure,
  VerifySignInParams,
  VerifySignInResult,
  SignMessageReview,
} from "./message-signing.js";

export { generateNonce, hexToBytes, bytesToHex } from "./utils.js";

export {
  pubkeyToAddress,
  isRougeAddress,
  formatAddress,
  addressToHash,
} from "./address.js";

export {
  computeCommitment,
  computeNullifier,
  generateRandomness,
  createShieldedNote,
} from "./shielded.js";
export type { ShieldedNote } from "./shielded.js";

export type {
  WalletKeys,
  ApiResponse,
  TransactionType,
  TransactionPayload,
  SignedTransaction,
  BlockHeader,
  Transaction,
  Block,
  NodeStats,
  UpgradeSchedule,
  TokenMetadata,
  TokenHolder,
  BalanceResponse,
  LiquidityPool,
  SwapQuote,
  PoolEvent,
  PoolStats,
  PriceSnapshot,
  NftCollection,
  NftToken,
  Validator,
  ValidatorStatus,
  BridgeConfig,
  BridgeWithdrawal,
  XrgeBridgeConfig,
  TransferParams,
  CreateTokenParams,
  SwapParams,
  CreatePoolParams,
  AddLiquidityParams,
  RemoveLiquidityParams,
  StakeParams,
  CreateNftCollectionParams,
  MintNftParams,
  BatchMintNftParams,
  TransferNftParams,
  BurnNftParams,
  LockNftParams,
  FreezeCollectionParams,
  BridgeWithdrawParams,
  BridgeClaimParams,
  XrgeBridgeClaimParams,
  XrgeBridgeWithdrawParams,
  SwapQuoteParams,
  TokenMetadataUpdateParams,
  NameEntry,
  ResolvedName,
  MailMessage,
  SendMailParams,
  MessengerWallet,
  MessengerConversation,
  MessengerFolder,
  MessengerNewMessageEvent,
  MessengerMessage,
  ShieldParams,
  ShieldedTransferParams,
  UnshieldParams,
  ShieldedStats,
  RollupStatus,
  RollupBatchResult,
  RollupSubmitParams,
  RollupSubmitResult,
  ApproveParams,
  TransferFromParams,
  ContractMetadata,
  ContractEvent,
  ContractCallResult,
  ContractQueryResult,
  ContractEventFrame,
  ContractStateValue,
  ContractEventsQuery,
  PublishContractOptions,
  PublishContractResult,
  ExecuteContractOptions,
  ExecuteContractResult,
  ContractAttach,
  NormalizedContractAttach,
  QueryContractOptions,
  TxReceipt,
  TxReceiptStatus,
  DeployContractParams,
  CallContractParams,
  FeeInfo,
  FinalityProof,
  MintTokenParams,
  VoteMessage,
  WsSubscribeMessage,
} from "./types.js";
