[book]
title = "RougeChain Documentation"
description = "Post-Quantum Secure Layer 1 Blockchain"
authors = ["RougeChain Team"]
language = "en"
src = "."

[build]
build-dir = "book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/cyberdreadx/rougechain-node"
git-repository-icon = "fa-github"
